environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - java -version
  - mvn --version

before_build:
  - cd reposilite-backend

build_script:
  - mvn clean install spring-boot:repackage

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
