reposilite:
  built-in-frontend: "on"
  workspace: ""

logging:
  level:
    org:
      springframework: WARN
      apache: WARN
      jline: ERROR
      panda_lang: WARN
      mongodb: WARN
    springfox: WARN

springfox:
  documentation:
    swagger:
      v2:
        path: "/api/docs"

spring:
  data:
    mongodb:
      uri: mongodb://username:password@host:port/database
  main:
    banner-mode: "off"