reposilite:
  built-in-frontend: "on"

logging:
  level:
    org:
      springframework: WARN
      apache: WARN
      jline: ERROR
      panda_lang: WARN
      mongodb: WARN
    springfox: WARN

springfox:
  documentation:
    swagger:
      v2:
        path: "/api/docs"

spring:
  main:
    banner-mode: "off" # prevent YAML cast to bool