reposilite:
  workspace: "reposilite-backend/src/test/workspace"

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/reposilite
