springfox:
  documentation:
    swagger:
      v2:
        path: "/api/docs"
logging:
  level:
    org:
      springframework: WARN
      apache: WARN
      jline: ERROR
      panda_lang: WARN
      mongodb: WARN
    springfox: WARN
spring:
  main:
    banner-mode: "off" # prevent YAML cast to bool