server:
  address: 127.0.0.1
  port: 3000

spring:
  main:
    banner-mode: "off"
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            scope:
              - user:email
              - read:user
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/user"

logging:
  level:
    org:
      springframework:
        security: DEBUG